# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='featuredImage',
            new_name='image',
        ),
    ]
