# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170606_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='image',
            new_name='url',
        ),
    ]
