# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170606_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
