# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featuredImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/featured/%Y/%m/%d'),
        ),
    ]
