# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170525_1528'),
        ('blog', '0003_blog_featuredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='about.Member'),
            preserve_default=False,
        ),
    ]
