# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nick_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
