# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170525_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick_name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
